In [53]:
#importing the dependencies

import numpy as np  #importing numpy - useful for making arrays
import pandas as pd #importing pandas - useful for dataset csv file, added to process data from the csv file for data frames, a strucutred table for analysis 
from sklearn.model_selection import train_test_split #function split data into training data which is split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score #help for process accuracy for the model
from sklearn.preprocessing import StandardScaler

In [10]:
#loading the csv dataset into the pandas dataframe
credit_card_data = pd.read_csv('Downloads/creditcard.csv')

In [11]:
#importing the first five rows of the credit card dataset via the pandas dataframe, we see the features of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [12]:
#first column is the time of the transcation present in seconds. elapsed time from the transaction.
#120 seconds, 2 minutes elapsed time from the first transaction 0 which happened -- time elapsed from 1st transaction. 
#colums v1-v28 - features about the transaction, cc details are sensitive so this is converted cc features to numeric letters through principle copnent analysis method.
#numeric values for prediction and analysis
#amount in the last column - USD
#class column - transaction is legit or not, 0 and 1. 0 - transaction is legit, 1 is fraudulent.

In [13]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [14]:
#172792.0 seconds 2 days of transaction from the first
#284806 data points as in transactions recorded.

In [15]:
#dataset information
#gives us null, coulumns, entery numbers.
#integer data type Class's data type int64 
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [16]:
#checkng no. of missing values in each column
credit_card_data.isnull().sum() #here we don't have missing values.

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [17]:
#distribution of legit transaction and fraudulent transaction 
credit_card_data['Class'].value_counts() #class is the column name

Class
0    284315
1       492
Name: count, dtype: int64

In [18]:
#data points for non-fraudulen and fraudulent transactions. 
# 284315 are non-fraudalent number of transactions represented by 0, and 492  are the number of fraudulent transactions represented by 1
#a very unbalanced data model becuase we have lesser data points for fraudulent to feed our machine learning model

In [19]:
#separating data for analysis

legit = credit_card_data[credit_card_data.Class == 0] #class column checking for 0 all the values in that row will be stored in the legit variable -- this is a pandas series data type.
fraud = credit_card_data[credit_card_data.Class == 1]

In [20]:
#printing the pandas series' shape
print(legit.shape)
print(fraud.shape) #number of transactions, number of columns

(284315, 31)
(492, 31)

In [21]:
#statistical measures of the data for the non-fraudulent, legit transactions

legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [22]:
#the number of data points we have in legit.amount and mean amount of the amount, etc. 
#so here percentage represents for example 25% is less than 5.67 dollars amount and 50% is less than 22 USD.

In [23]:
#statistical measures of the data for the fraudulent transactions
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [24]:
#comparing the values of both transactions
credit_card_data.groupby('Class').mean() #class is 0 or 1

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [25]:
#mean of all the columns of time, v1, v2 etc of 0 and 1. ML algorithm can find legit or fraud. this difference in the values in 0 and 1 of each column is important to detect.

In [26]:
#Under Sampling 
#Build a sample datasete containing similar distrubution of legit transaction and fraud transactions (492 values)
#so we will distribute 492 values from the legit 284315 transactions, so that there is a uniform distribution of data between legit and fraud - 492 each
#we can make better predictions using ML

In [27]:
legit_sample = legit.sample(n=492)

In [28]:
#Concatinating two data frames

new_dataset = pd.concat([legit_sample, fraud], axis =0) #axis=0 -> rows, and axis=1 -> columns of the data

In [29]:
new_dataset.head() #random

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
141560,84386.0,1.207692,-1.287230,0.073515,-1.366495,-1.273867,-0.551909,-0.599214,-0.084918,-2.361008,...,-0.404792,-1.129696,0.151816,0.144977,0.049463,-0.539822,-0.002477,0.027621,132.80,0
13119,23031.0,-0.277467,1.281406,1.102467,0.060715,0.584215,-0.438407,0.653999,-0.145332,0.826621,...,-0.460589,-0.964520,-0.117699,-0.545890,-0.044929,0.082670,0.223228,0.085041,2.69,0
229243,145849.0,2.055079,-0.144315,-1.675306,0.468070,0.102798,-1.306209,0.427408,-0.367945,0.576727,...,-0.039623,0.013416,0.077573,-0.056553,0.124074,0.570921,-0.104853,-0.078173,19.99,0
7178,9410.0,-6.040307,2.004847,0.262102,-0.495953,-0.389058,-0.770477,0.511107,-0.439778,5.521981,...,-1.340828,-0.072968,0.735883,0.373550,0.961047,0.294579,0.434053,0.046936,0.01,0
223103,143247.0,-0.703007,0.537546,-0.330289,-0.617870,0.745441,-0.807536,1.331169,-0.170652,-0.245595,...,0.320456,0.906608,-0.144651,-0.435702,-0.031291,-0.179348,0.065993,0.177519,113.00,0

In [30]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [31]:
#checking class for 0 and 1 to determine fraud and legit

In [32]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [33]:
#uniform values distributed

In [34]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95511.359756,0.092218,-0.005128,-0.063939,0.043925,-0.063511,0.044406,0.156507,-0.021098,0.079464,...,-0.105548,-0.048020,0.019356,-0.022223,0.024794,0.005984,-0.006837,-0.006642,0.023310,88.941728
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [35]:
#Spliting data into features (V1, V2, V3) and targets (0, 1).

X = new_dataset.drop(columns= 'Class', axis=1) #drops the class column
Y = new_dataset['Class'] #represents the class/labels

In [36]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
141560   84386.0  1.207692 -1.287230  0.073515 -1.366495 -1.273867 -0.551909
13119    23031.0 -0.277467  1.281406  1.102467  0.060715  0.584215 -0.438407
229243  145849.0  2.055079 -0.144315 -1.675306  0.468070  0.102798 -1.306209
7178      9410.0 -6.040307  2.004847  0.262102 -0.495953 -0.389058 -0.770477
223103  143247.0 -0.703007  0.537546 -0.330289 -0.617870  0.745441 -0.807536
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
141560 -0.599214 -0.084918 -2.361008  ... -0.148718 -0.404792 -1.129696
13119   0.653999 -0.145332  0.826621  ...  0.147659 -0.460589 -0.964520
229243  0.427408 -0.367945  0.576727  ... -0.294603 -0.039623  0.013416
7178    0.511107 -0.439778  5.521981  ...  0.203670 -1.340828 -0.072968
223103  1.331169 -0.170652 -0.245595  ... -0.188730  0.320456  0.906608
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
141560  0.151816  0.144977  0.049463 -0.539822 -0.002477  0.027621  132.80
13119  -0.117699 -0.545890 -0.044929  0.082670  0.223228  0.085041    2.69
229243  0.077573 -0.056553  0.124074  0.570921 -0.104853 -0.078173   19.99
7178    0.735883  0.373550  0.961047  0.294579  0.434053  0.046936    0.01
223103 -0.144651 -0.435702 -0.031291 -0.179348  0.065993  0.177519  113.00
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [37]:
#Class column dropped ^

In [43]:
print(Y) #labels

141560    0
13119     0
229243    0
7178      0
223103    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [58]:
#Split data into Training Data and Testing Data

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state =2) #x are the features/values of the 30 columns #y is the target variable/label/class, test size is 20% testing data we want. 80% is data is training data. 
#stratify is whne you is used to ensure that the split maintains the same proportion of different classes in both the training and testing sets as they are in the original dataset. 
#This is especially important when you have an imbalanced dataset, where some classes are more frequent than others.
#example if you have a dataset with 1000 samples where 900 belong to class 0 and 100 belong to class 1. 
#If you split this data without stratification, you might end up with a training set heavily skewed towards one class, 
#which can bias your model. By using stratify=y, we ensure that both the training and testing sets have approximately 90% of class 0 and 10% of class 1, reflecting the original dataset's distribution.



scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)


X_test_scaled = scaler.transform(X_test)

In [59]:
print(X.shape, X_train.shape, X_test.shape) #984 values in the original data set of X, then X_train has 80% and X_test has 20%, we've split the data

(984, 30) (787, 30) (197, 30)

In [60]:
#Model Training  - through logistic regression model for binary classification problems.

model = LogisticRegression(max_iter=1000)

In [62]:
#training the lgosistic regression model with the training data
model.fit(X_train_scaled, Y_train) #used fit to train the model. 
#then we will make predictions from this ML model
#we have lesser data points, in case of deep learning, we use more data points, training takes long time.
#this is numeric data, usually we have image data

LogisticRegression(max_iter=1000)

In [66]:
#finding performance of the model

#Accuracy Score on training data using X_train, and compare it to the original model in the Y_train
X_train_scaled_prediction = model.predict(X_train_scaled) #training all the labels for the training data, stored in this
training_data_accuracy = accuracy_score(X_train_scaled_prediction, Y_train) #then compare the values predicted by the model, with the original lavels stored in the Y-train
#stored in the training_data_accuracy

In [74]:
print('Accuracy on Training data: ', training_data_accuracy)
#we test training data to check if the training and test data accuracy are very different; if they are different it means that our model is underfitted or overfitted.
#overfitting - model is doing well on training data - becuause model is overtrained on the training data as it has read it before.
#underfitted - over generalize learning

Accuracy on Training data:  0.9529860228716646

In [ ]:
#good score if more than 75. so 95/100 predictions are predicted of the training data by the model. 
#test data prediction is important. student studyign for math, practicing with problems. those problems will be trianing data. the examiner can ask the exam not present in the book.
#so test is evaluate with data it hasn't seen. it has seen the X_train data, but not the X_test data.

In [72]:
X_test_prediction = model.predict(X_test_scaled)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [73]:
print('Accuracy on Test data: ', test_data_accuracy)

Accuracy on Test data:  0.9187817258883249

In [ ]:
# 91% good score. similar score on training and test data - good predictions.